# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vsTd4piYmI0oeT4UbXTJTlc_xkwDKNW7

1) Apresente o total de itens da lista exibida abaixocom os meses do ano.Retorno de um número inteiro.
"""

listaMeses = ['Janeiro', 'Fevereiro', 'Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro']
print(len(listaMeses))

"""2)Junte as duas listas emuma terceira lista vazia. Concatene as duas listas."""

primeiroSemestre = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun']
segundoSemestre =  ['Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']

novaLista = primeiroSemestre + segundoSemestre 
print(novaLista)

"""3)imprima de maneira separada o primeiro e último iten da lista"""

ListaValores = [2200, 3400, 5750,800,2000,1350]

print('Ultimo item da lista ',ListaValores [5])
print('Ultimo item da lista ',ListaValores[0])

"""4)Adicione o nome Paula Fernandes na posição 2."""

Nomes = ['Suzy', 'Janaina', 'Claudevan', 'Maria Clara']

Nomes.insert(2,'Paula Fernades')
print(Nomes)

"""5) Alter o nome Sony para Sony Vaio. 
Remova o nome Compaq da lista. 
"""

Nomes2 = ['Dell', 'Apple', 'Sony', 'Acer', 'Compaq', 'Positivo', 'Lenovo']

Nomes2[2] = 'Sony Vaio'
Nomes2.remove('Compaq')
print(Nomes2)

"""6)Imprima em ordem numérica crescente (do menor para o maior) a lista exibida"""

listadeNumeros =[ 230,430,100,52,670,1212,321,89,96,34,20,89,99,710 ]
listadeNumeros.sort(reverse=False)

print(listadeNumeros)

"""7) Imprima em ordem numérica decrescente (do maior para o menor) a lista exibida abaixo."""

listadeNumeros =[ 230,430,100,52,670,1212,321,89,96,34,20,89,99,710 ]
listadeNumeros.sort(reverse=True)

print(listadeNumeros)

"""8) Escreva um programa que leia uma lista(10 valores) de números inteiros e imprima a soma de todos os números pares da lista. A entrada dos valores deve ser informada pelo usuário."""

minhaLista=[]
sum = 0
for i in range(0,10):
  minhaLista.append(int(input('Digite os valores para adionar à lista:')))
  if(minhaLista[i] % 2) == 0:
   sum += minhaLista[i]
  
print(sum)

"""9) Escreva um programa que leia uma lista(10 valores) de números inteiros e imprima a média dos números da lista. Mais uma vez os valores devem ser digitados pelo usuário.

ESSE COD TA DANDO ERRO NO COLAB, MASSSS ELE TA CERTO.

COLAB N PRESTA!!!!!!
"""

minhaLista2=[]

for i in range(0,10):
  minhaLista2.append(float(input('Digite os valores para adicionar à lista: ')))

soma = sum(minhaLista2)
media = float(soma)/10
# media = media/5
print(media)