# -*- coding: utf-8 -*-
"""listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ulI2NYyImiKukY8hFbdCD8n6JCT7lIty
"""

lista1=[1,2,3,4,5,6,7,8,9,10]
 
 lista2=[1, 2,'Junior','Aline', 4,4.5]

 print(lista1)
 print(30* '*')
 print(lista2)

 lista2.append('Aline')#adiciona um dado na ultima posição
 print (lista2)

nomes = ['camila', 'Luan', 'Debora', 'Edmilson']
 print (nomes)

 nomes.insert (2, 'Michael') #INSERT: insere o dado na posição indicada

 print (nomes)

linguagens=['python','Java','JavaScript','C']
print(linguagens)

linguagens[3] = 'C++' #UPDATE: atualiza o dado indicado
print(linguagens)

lista2.remove('Junior') #DELETE: removendo um dado da lista.

 print(lista2)

lista3 =['Ana Julia ', 'Carlão', 'Joaõ Cleber','Dna. Sônia']
del lista3[1] # DERETE WHERE: deleta uma posição especifica

print(lista3)

listanumeros=[100,200,300,459,400,500]
print(listanumeros)

listanumeros.pop()#remove o ultimo registro
print(listanumeros)

listanumeros.pop(-4)#remove o registro indicado no índice
print(listanumeros)

"""POP VS DEL= o pop começa a remover da ultima posição enquanto o del começa a remover da primeira


"""

lista4 =['Corinthians', 'São paulo', 'Santos', 'Palmeiras']
print(lista4)

print(lista4.index('Corinthians')) #Ele vai retornar a posição do registro.

print('Portuguesa'in lista4)# Ele informa se o valor informado esta presente no vetor.
print('Palmeiras'in lista4)

umaLista =[1,2,3]
outraLista = [10,20,30]
novaLista =umaLista + outraLista #concatena uma lista com a outra
print(novaLista)

lista = [1,2,3,4,5]
listaRepeticao = lista * 3 #repete a lista de acordo com a quantidade informada
print(listaRepeticao)

lista5 = [2,4,5,6]
print(sum(lista5)) #soma os valores presentes no vetor e obvio que não da pra somar string, apenas valores numericos

lista01 =[10,20,30,40,50,60,70,80,90,100]

print(min(lista01)) # mostra o menor valor do vetor 
print(max(lista01)) # mostra o maior valor no vetor

lista6 = [10,20,30,50,70] 
print(len(lista6)) # contar o total de elementos de uma lista.

lista01 =[10,20,30,40,50,60,70,80,90,100]

print('Primeiro item da lista ', lista01[0]) 
print('Ultimo item da lista ',lista01[-1])
